friends = {   'alcaras': [   'Windrunner',
                             'Phantom Assassin',
                             'Crystal Maiden',
                             'Lich',
                             'Dark Seer',
                             'Shadow Demon',
                             'Drow Ranger',
                             'Venomancer',
                             'Enigma',
                             'Tidehunter',
                             'Leshrac',
                             'Chaos Knight'],
              'boozie': [   'Bounty Hunter',
                            'Shadow Shaman',
                            'Viper',
                            'Slardar',
                            'Windrunner',
                            'Lich',
                            'Mirana',
                            'Dragon Knight',
                            'Lina',
                            'Pudge',
                            'Tidehunter',
                            'Rubick',
                            'Omniknight',
                            'Weaver',
                            'Dazzle',
                            'Leshrac',
                            'Queen of Pain',
                            'Anti-Mage',
                            'Sven',
                            'Huskar',
                            'Skeleton King',
                            'Lion',
                            'Disruptor',
                            'Broodmother',
                            'Undying',
                            'Brewmaster',
                            'Drow Ranger',
                            'Silencer'],
              'kry': ['Doom Bringer'],
              'rip': [   'Pugna',
                         'Disruptor',
                         'Sven',
                         'Magnus',
                         'Jakiro',
                         'Crystal Maiden',
                         'Night Stalker',
                         'Keeper of the Light',
                         'Pudge',
                         'Shadow Demon',
                         'Venomancer'],
              'speed': [   'Ogre Magi',
                           'Lion',
                           'Gyrocopter',
                           'Pudge',
                           'Drow Ranger',
                           'Jakiro',
                           'Lich'],
              'vorsh': [   'Ancient Apparition',
                           'Omniknight',
                           'Sniper',
                           'Zeus',
                           'Pugna',
                           'Leshrac',
                           'Phantom Lancer',
                           'Kunkka',
                           'Storm Spirit',
                           'Spirit Breaker',
                           'Enigma',
                           'Axe',
                           'Venomancer'],
              'wyv': [   'Viper',
                         'Juggernaut',
                         'Skeleton King',
                         'Bane',
                         'Windrunner',
                         'Lich',
                         'Slardar',
                         'Drow Ranger',
                         'Lion',
                         'Venomancer',
                         'Faceless Void',
                         'Rubick',
                         'Jakiro']}
