lanes = {
    "Solo Mid" : ["Ancient Apparition",
                  "Batrider",
                  "Beastmaster",
                  "Bloodseeker",
                  "Chaos Knight",
                  "Huskar",
                  "Invoker",
                  "Lion",
                  "Lina",
                  "Magnus",
                  "Nightstalker",
                  "Nyx Assassin",
                  "Pudge",
                  "Pugna",
                  "Rubick",
                  "Shadow Fiend",
                  "Shadow Shaman",
                  "Storm Spirit",
                  "Templar Assassin",
                  "Tinker",
                  "Tiny",
                  "Queen of Pain",
                  "Zeus"],
    "Solo Side" : ["Bounty Hunter",
                   "Broodmother",
                   "Clinkz",
                   "Clockwerk",
                   "Dark Seer",
                   "Mirana",
                   "Windrunner",
                   "Puck",
                   "Weaver"],
    "Hard Lane" : ["Bane",
                   "Brewmaster",
                   "Death Prophet",
                   "Dragon Knight",
                   "Earthshaker",
                   "Gyrocopter",
                   "Jakiro",
                   "Keeper of the Light",
                   "Kunkka",
                   "Leshrac",
                   "Ogre Magi",
                   "Omniknight",
                   "Razor",
                   "Sand King",
                   "Silencer",
                   "Shadow Demon",
                   "Slardar",
                   "Sven",
                   "Tidehunter",
                   "Treant Protector",
                   "Undying",
                   "Visage",
                   "Witch Doctor"],
}


