pickbans = ["Rubick",
            "Chen",
            "Dark Seer",
            "Leshrac",
            "Naga Siren",
            "Lycanthrope",
            "Tidehunter",
            "Invoker",
            "Nature's Prophet",
            "Morphling",
            "Venomancer",
            "Enchantress",
            "Broodmother",
            "Lone Druid",
            "Enigma",
            "Templar Assassin",
            "Brewmaster",
            "Anti-Mage",
            "Windrunner",
            "Chaos Knight",
            "Shadow Shaman",
            "Beastmaster",
            "Sand King",
            "Tinker",
            "Bounty Hunter",
            "Queen of Pain",
            "Shadow Demon",
            "Disruptor",
            "Wisp",
            "Night Stalker",
            "Tiny",
            "Pudge",
            "Crystal Maiden",
            "Storm Spirit",
            "Ancient Apparition",
            "Juggernaut",
            "Dragon Knight",
            "Keeper of the Light",
            "Lina",
            "Luna",
            "Puck",
            "Lich",
            "Batrider",
            "Earthshaker",
            "Faceless Void",
            "Vengeful Spirit",
            "Clinkz",
            "Shadow Fiend",
            "Mirana",
            "Dazzle",
            "Death Prophet",
            "Kunkka",
            "Slardar",
            "Axe",
            "Bane",
            "Drow Ranger",
            "Phantom Assassin",
            "Riki",
            "Lifestealer",
            "Lion",
            "Nyx Assassin",
            "Pugna",
            "Undying",
            "Ursa",
            "Visage",
            "Witch Doctor",
            "Alchemist",
            "Gyrocopter",
            "Huskar",
            "Omniknight",
            "Outworld Destroyer",
            "Phantom Lancer",
            "Spirit Breaker",
            "Sven",
            "Treant Protector",
            "Bloodseeker",
            "Clockwerk",
            "Doom Bringer",
            "Jakiro",
            "Magnus",
            "Meepo",
            "Necrolyte",
            "Ogre Magi",
            "Razor",
            "Silencer",
            "Skeleton King",
            "Sniper",
            "Spectre",
            "Viper",
            "Warlock",
            "Weaver",
            "Zeus",
            "Centaur Warrunner"]
