# heroes to play
# - darkseer
# - engima
# - windrunner
# - veno
# - shadow demon
# - chaos knight


# heroes i have not won with
# heroes i have not lost with
rotation = [
    "Alchemist",
    "Anti-Mage",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Broodmother",
    "Clinkz",
    "Clockwerk",
    "Death Prophet",
    "Disruptor",
    "Doom Bringer",
    "Dragon Knight",
    "Earthshaker",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Gyrocopter",
    "Huskar",
    "Invoker",
    "Juggernaut",
    "Keeper of the Light",
    "Kunkka",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Magnataur",
    "Meepo",
    "Morphling",
    "Naga Siren",
    "Necrolyte",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Outworld Destroyer",
    "Phantom Lancer",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Sniper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Templar Assassin",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Viper",
    "Visage",
    "Warlock",
    "Wisp",
    "Witch Doctor",
    "Zeus",
    ]
