# heroes to play
# - darkseer
# - engima
# - windrunner
# - veno
# - shadow demon
# - chaos knight


# heroes with fewer with 5 games played
underfive = [
    "Slark",
    "Centaur Warrunner",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Broodmother",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Dazzle",
    "Disruptor",
    "Doom Bringer",
    "Dragon Knight",
    "Earthshaker",
    "Enchantress",
    "Faceless Void",
    "Gyrocopter",
    "Huskar",
    "Invoker",
    "Jakiro",
    "Juggernaut",
    "Kunkka",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycanthrope",
    "Magnus",
    "Meepo",
    "Mirana",
    "Morphling",
    "Naga Siren",
    "Nature's Prophet",
    "Necrolyte",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Outworld Destroyer",
    "Phantom Lancer",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skeleton King",
    "Sniper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Templar Assassin",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Viper",
    "Visage",
    "Warlock",
    "Weaver",
    "Wisp",
    "Witch Doctor",
    "Zeus",
    ]
